/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DataRouteImport } from './routes/data'
import { Route as EmployeeAssessmentRouteImport } from './routes/employee-assessment'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as OrgChartRouteImport } from './routes/org-chart'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeAssessmentRoute = EmployeeAssessmentRouteImport.update({
  id: '/employee-assessment',
  path: '/employee-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgChartRoute = OrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/data': typeof DataRoute
  '/employee-assessment': typeof EmployeeAssessmentRoute
  '/goals': typeof GoalsRoute
  '/issues': typeof IssuesRoute
  '/meeting': typeof MeetingRoute
  '/org-chart': typeof OrgChartRoute
  '/people': typeof PeopleRoute
  '/signin': typeof SigninRoute
  '/todos': typeof TodosRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/data': typeof DataRoute
  '/employee-assessment': typeof EmployeeAssessmentRoute
  '/goals': typeof GoalsRoute
  '/issues': typeof IssuesRoute
  '/meeting': typeof MeetingRoute
  '/org-chart': typeof OrgChartRoute
  '/people': typeof PeopleRoute
  '/signin': typeof SigninRoute
  '/todos': typeof TodosRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/data': typeof DataRoute
  '/employee-assessment': typeof EmployeeAssessmentRoute
  '/goals': typeof GoalsRoute
  '/issues': typeof IssuesRoute
  '/meeting': typeof MeetingRoute
  '/org-chart': typeof OrgChartRoute
  '/people': typeof PeopleRoute
  '/signin': typeof SigninRoute
  '/todos': typeof TodosRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/data'
    | '/employee-assessment'
    | '/goals'
    | '/issues'
    | '/meeting'
    | '/org-chart'
    | '/people'
    | '/signin'
    | '/todos'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/data'
    | '/employee-assessment'
    | '/goals'
    | '/issues'
    | '/meeting'
    | '/org-chart'
    | '/people'
    | '/signin'
    | '/todos'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/data'
    | '/employee-assessment'
    | '/goals'
    | '/issues'
    | '/meeting'
    | '/org-chart'
    | '/people'
    | '/signin'
    | '/todos'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  DataRoute: typeof DataRoute
  EmployeeAssessmentRoute: typeof EmployeeAssessmentRoute
  GoalsRoute: typeof GoalsRoute
  IssuesRoute: typeof IssuesRoute
  MeetingRoute: typeof MeetingRoute
  OrgChartRoute: typeof OrgChartRoute
  PeopleRoute: typeof PeopleRoute
  SigninRoute: typeof SigninRoute
  TodosRoute: typeof TodosRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-assessment': {
      id: '/employee-assessment'
      path: '/employee-assessment'
      fullPath: '/employee-assessment'
      preLoaderRoute: typeof EmployeeAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-chart': {
      id: '/org-chart'
      path: '/org-chart'
      fullPath: '/org-chart'
      preLoaderRoute: typeof OrgChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  DataRoute: DataRoute,
  EmployeeAssessmentRoute: EmployeeAssessmentRoute,
  GoalsRoute: GoalsRoute,
  IssuesRoute: IssuesRoute,
  MeetingRoute: MeetingRoute,
  OrgChartRoute: OrgChartRoute,
  PeopleRoute: PeopleRoute,
  SigninRoute: SigninRoute,
  TodosRoute: TodosRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
