/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as RocksRouteImport } from './routes/rocks'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as VtoRouteImport } from './routes/vto'
import { Route as PeopleAnalyzerRouteImport } from './routes/people/analyzer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const RocksRoute = RocksRouteImport.update({
  id: '/rocks',
  path: '/rocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const VtoRoute = VtoRouteImport.update({
  id: '/vto',
  path: '/vto',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleAnalyzerRoute = PeopleAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => PeopleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/issues': typeof IssuesRoute
  '/people': typeof PeopleRouteWithChildren
  '/rocks': typeof RocksRoute
  '/scorecard': typeof ScorecardRoute
  '/signin': typeof SigninRoute
  '/todos': typeof TodosRoute
  '/vto': typeof VtoRoute
  '/people/analyzer': typeof PeopleAnalyzerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/issues': typeof IssuesRoute
  '/people': typeof PeopleRouteWithChildren
  '/rocks': typeof RocksRoute
  '/scorecard': typeof ScorecardRoute
  '/signin': typeof SigninRoute
  '/todos': typeof TodosRoute
  '/vto': typeof VtoRoute
  '/people/analyzer': typeof PeopleAnalyzerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/issues': typeof IssuesRoute
  '/people': typeof PeopleRouteWithChildren
  '/rocks': typeof RocksRoute
  '/scorecard': typeof ScorecardRoute
  '/signin': typeof SigninRoute
  '/todos': typeof TodosRoute
  '/vto': typeof VtoRoute
  '/people/analyzer': typeof PeopleAnalyzerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart'
    | '/issues'
    | '/people'
    | '/rocks'
    | '/scorecard'
    | '/signin'
    | '/todos'
    | '/vto'
    | '/people/analyzer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart'
    | '/issues'
    | '/people'
    | '/rocks'
    | '/scorecard'
    | '/signin'
    | '/todos'
    | '/vto'
    | '/people/analyzer'
  id:
    | '__root__'
    | '/'
    | '/chart'
    | '/issues'
    | '/people'
    | '/rocks'
    | '/scorecard'
    | '/signin'
    | '/todos'
    | '/vto'
    | '/people/analyzer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartRoute: typeof ChartRoute
  IssuesRoute: typeof IssuesRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  RocksRoute: typeof RocksRoute
  ScorecardRoute: typeof ScorecardRoute
  SigninRoute: typeof SigninRoute
  TodosRoute: typeof TodosRoute
  VtoRoute: typeof VtoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rocks': {
      id: '/rocks'
      path: '/rocks'
      fullPath: '/rocks'
      preLoaderRoute: typeof RocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vto': {
      id: '/vto'
      path: '/vto'
      fullPath: '/vto'
      preLoaderRoute: typeof VtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/analyzer': {
      id: '/people/analyzer'
      path: '/analyzer'
      fullPath: '/people/analyzer'
      preLoaderRoute: typeof PeopleAnalyzerRouteImport
      parentRoute: typeof PeopleRoute
    }
  }
}

interface PeopleRouteChildren {
  PeopleAnalyzerRoute: typeof PeopleAnalyzerRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleAnalyzerRoute: PeopleAnalyzerRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartRoute: ChartRoute,
  IssuesRoute: IssuesRoute,
  PeopleRoute: PeopleRouteWithChildren,
  RocksRoute: RocksRoute,
  ScorecardRoute: ScorecardRoute,
  SigninRoute: SigninRoute,
  TodosRoute: TodosRoute,
  VtoRoute: VtoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
